# Generated by Django 3.1.3 on 2020-11-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('departure_city', models.CharField(max_length=50)),
                ('departure_time', models.IntegerField()),
                ('arrival_city', models.CharField(max_length=50)),
                ('arrival_time', models.IntegerField()),
            ],
        ),
    ]
