# Generated by Django 3.1.3 on 2020-11-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightdetails',
            name='arrival_time',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='flightdetails',
            name='departure_time',
            field=models.BigIntegerField(),
        ),
    ]
